-- This configuration is generated by matugen
-- Changing these variables with matugen still enabled will overwrite them.

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local text_color = "rgba(dee2f2FF)"
local entry_background_color = "rgba(161c2711)"
local entry_border_color = "rgba(92909255)"
local entry_color = "rgba(dee2f2FF)"
local font_family = "Google Sans Flex Medium"
local font_family_clock = "Google Sans Flex Medium"
local font_material_symbols = "Material Symbols Rounded"

local background_image = "/home/damindu/Pictures/backgrounds/8.PNG"
