set -ga terminal-overrides ",screen-256color*:Tc"
set-option -g default-terminal "screen-256color"
# set -g status-style 'bg=#4c566a fg=#5eacd3'
set -g status-style 'bg=#6292A5 fg=#1C1D1D'
set -s escape-time 0

unbind -n C-n
unbind -n C-p
