-- You can make apps auto-start here
-- Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing

-- Input method
-- exec-once = fcitx5

-- KDEConnect
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.on("hyprland.start", function()
    hl.exec_cmd("kdeconnect-indicator")
end)

