# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# ######## Window rules ########

windowrule = match:class discord, workspace 2 silent
windowrule = match:class notion-electron, workspace 3
windowrule = match:class net.lutris.Lutris, workspace 3
windowrule = match:class pavucontrol-qt, float 1
windowrule = match:class Waydroid, float 1, size (monitor_w*0.23) (monitor_h*0.8)
windowrule = match:class waydroid.*, float 1, size (monitor_w*0.23) (monitor_h*0.8)
# windowrule = match:class Waydroid, float 1
# windowrule = match:class waydroid.*, float 1
windowrule = match:class wihotspot, float 1 
windowrule = match:class scrcpy, float 1, size (monitor_w*0.167) (monitor_h*0.64)
windowrule = match:class org.kde.dolphin, float 1, size (monitor_w*0.6) (monitor_h*0.6)
windowrule = match:class dolphin, float 1, center 1, size (monitor_w*0.6) (monitor_h*0.6)
windowrule = match:class chrome-nngceckbapebfimnlniiiahkandclblb-Default, float 1 # Bitwarden
windowrule = match:class steam, workspace 4
windowrule = match:title Sign\sin\sto\sSteam, center 1

windowrule {
    name = "Float steam menus"
    match:class = steam
    match:title = negative:Steam|Steam\sBig\sPicture\sMode

    float = 1
}

windowrule {
    name = "Make steam big picture mode full screen"
    match:title = Steam\sBig\sPicture\sMode

    fullscreen = 1
}

windowrule {
    name = "Fix Forza"
    match:class = negative:steam
    match:title = Forza\sHorizon\s4

    rounding = 0
    fullscreen = 1
}

# Terminal blur
windowrule = opacity 0.89 override 0.79 override, match:class Alacritty, no_blur off

# Uncomment to apply global transparency to all windows:
# windowrule = opacity 0.89 override 0.89 override, match:class .*

# Disable blur for all xwayland apps
# windowrule = no_blur on, match:xwayland 1
