-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Source: ~/.config/hypr/hyprlock/colors.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("hyprlock.colors")

-- TODO: manual review — unknown section 'background {' on line 3
-- TODO: manual review — unknown section 'input-field {' on line 6

-- TODO: manual review — unknown section 'label {' on line 22

-- TODO: manual review — unknown section 'label {' on line 33
-- Caps Lock Warning

-- TODO: manual review — unknown section 'label {' on line 45
-- Clock
-- TODO: manual review — unknown section 'label {' on line 56
-- Date

-- TODO: manual review — unknown section 'label {' on line 68
-- User

-- TODO: manual review — unknown section 'label {' on line 83
-- Status
