-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local lock_cmd = "hyprctl dispatch global quickshell:lock & pidof qs quickshell hyprlock || hyprlock"
-- $lock_cmd = pidof hyprlock || hyprlock
local suspend_cmd = "systemctl suspend || loginctl suspend"
local poweroff_cmd = "systemctl poweroff"

-- TODO: manual review — unknown section 'listener {' on line 13

-- TODO: manual review — unknown section 'listener {' on line 18
hl.config({
  general = {
    lock_cmd = lock_cmd,
    before_sleep_cmd = "loginctl lock-session",
    after_sleep_cmd = "hyprctl dispatch global quickshell:lockFocus",
    inhibit_sleep = 3,
  },
  --
  -- listener {
  --     timeout = 10800 # 3 hours
  --     on-timeout = $poweroff_cmd
  -- }
})
