-- This file sources other files in `hyprland` and `custom` folders
-- You wanna add your stuff in files in `custom`

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

QsConfig = "ii"
hl.define_submap("global", function()
  -- Defaults
end)

-- Source: hyprland/env.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("hyprland.env")
-- Source: hyprland/execs.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("hyprland.execs")
-- Source: hyprland/general.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("hyprland.general")
-- Source: hyprland/rules.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("hyprland.rules")
-- Source: hyprland/colors.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("hyprland.colors")
-- Source: hyprland/keybinds.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("hyprland.keybinds")

-- Custom
-- Source: custom/env.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("custom.env")
-- Source: custom/execs.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("custom.execs")
-- Source: custom/general.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("custom.general")
-- Source: custom/rules.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("custom.rules")
-- Source: custom/keybinds.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("custom.keybinds")

-- nwg-displays support
-- Source: workspaces.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("workspaces")
-- Source: monitors.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("monitors")

hl.on("config.reloaded", function()
  hl.exec_cmd("hyprctl dispatch submap global")
end)
