-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- TODO: manual review — plugin section ''. The new Lua API exposes plugins via hl.plugin.<name>(...) — wire up per the plugin's docs.
--[[
  hyprbars { ... }
]]

hl.window_rule({
  match = {
    pin = 1,
  },
  border_color = "rgba(c1c6d6AA) rgba(c1c6d677)",
})

hl.config({
  general = {
    col = {
      active_border = "rgba(92909277)",
      inactive_border = "rgba(47464855)",
    },
  },
  misc = {
    background_color = "rgba(131315FF)",
  },
})
