-- Lines ending with `# [hidden]` won't be shown on cheatsheet
-- Lines starting with #! are section headings

--!
--#! Shell
-- These absolutely need to be on top, or they won't work consistently
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.bind("SUPER + X", hl.dsp.global("quickshell:searchToggle"), { description = "Toggle search" })
hl.bind("SUPER + SUPER_R", hl.dsp.global("quickshell:searchToggleRelease"),
  { ignore_mods = true, description = "Toggle search" })
hl.bind("SUPER + SUPER_L", hl.dsp.exec_cmd("qs -c " .. QsConfig .. " ipc call TEST_ALIVE || pkill fuzzel || fuzzel"))
hl.bind("SUPER + SUPER_R", hl.dsp.exec_cmd("qs -c " .. QsConfig .. " ipc call TEST_ALIVE || pkill fuzzel || fuzzel"))
-- hl.bind("SUPER + catchall", hl.dsp.global("quickshell:searchToggleReleaseInterrupt"),
--   { non_consuming = true, transparent = true, ignore_mods = true })
hl.bind("CTRL + SUPER_L", hl.dsp.global("quickshell:searchToggleReleaseInterrupt"))
hl.bind("CTRL + SUPER_R", hl.dsp.global("quickshell:searchToggleReleaseInterrupt"))
hl.bind("SUPER + mouse:272", hl.dsp.global("quickshell:searchToggleReleaseInterrupt"))
hl.bind("SUPER + mouse:273", hl.dsp.global("quickshell:searchToggleReleaseInterrupt"))
hl.bind("SUPER + mouse:274", hl.dsp.global("quickshell:searchToggleReleaseInterrupt"))
hl.bind("SUPER + mouse:275", hl.dsp.global("quickshell:searchToggleReleaseInterrupt"))
hl.bind("SUPER + mouse:276", hl.dsp.global("quickshell:searchToggleReleaseInterrupt"))
hl.bind("SUPER + mouse:277", hl.dsp.global("quickshell:searchToggleReleaseInterrupt"))
hl.bind("SUPER + mouse_up", hl.dsp.global("quickshell:searchToggleReleaseInterrupt"))
hl.bind("SUPER + mouse_down", hl.dsp.global("quickshell:searchToggleReleaseInterrupt"))

hl.bind("SUPER_L", hl.dsp.global("quickshell:workspaceNumber"), { transparent = true, ignore_mods = true })
hl.bind("SUPER_R", hl.dsp.global("quickshell:workspaceNumber"), { transparent = true, ignore_mods = true })
hl.bind("ALT + Tab", hl.dsp.global("quickshell:overviewWorkspacesToggle"))
hl.bind("SUPER + V", hl.dsp.global("quickshell:overviewClipboardToggle"),
  { description = "Clipboard history >> clipboard" })
hl.bind("SUPER + Period", hl.dsp.global("quickshell:overviewEmojiToggle"), { description = "Emoji >> clipboard" })
hl.bind("SUPER + A", hl.dsp.global("quickshell:sidebarLeftToggle"))
hl.bind("SUPER+ALT + A", hl.dsp.global("quickshell:sidebarLeftToggleDetach"))
-- bind = SUPER, B, global, quickshell:sidebarLeftToggle # [hidden]
-- bind = SUPER, O, global, quickshell:sidebarLeftToggle # [hidden]
hl.bind("SUPER + N", hl.dsp.global("quickshell:sidebarRightToggle"), { description = "Toggle right sidebar" })
hl.bind("SUPER + Slash", hl.dsp.global("quickshell:cheatsheetToggle"), { description = "Toggle cheatsheet" })
-- bindd = SUPER, K, Toggle on-screen keyboard, global, quickshell:oskToggle # Toggle on-screen keyboard
-- bindd = SUPER, M, Toggle media controls, global, quickshell:mediaControlsToggle # Toggle media controls
hl.bind("SUPER + G", hl.dsp.global("quickshell:overlayToggle"))
hl.bind("CTRL+ALT + Delete", hl.dsp.global("quickshell:sessionToggle"), { description = "Toggle session menu" })
hl.bind("SUPER + B", hl.dsp.global("quickshell:barToggle"), { description = "Toggle bar" })
hl.bind("CTRL+ALT + Delete",
  hl.dsp.exec_cmd("qs -c " .. QsConfig .. " ipc call TEST_ALIVE || pkill wlogout || wlogout -p layer-shell"))
hl.bind("SHIFT+SUPER+ALT + Slash", hl.dsp.exec_cmd("qs -p ~/.config/quickshell/" .. QsConfig .. "/welcome.qml"))

hl.bind("XF86MonBrightnessUp",
  hl.dsp.exec_cmd("qs -c " .. QsConfig .. " ipc call brightness increment || brightnessctl s 5%+"),
  { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown",
  hl.dsp.exec_cmd("qs -c " .. QsConfig .. " ipc call brightness decrement || brightnessctl s 5%-"),
  { locked = true, repeating = true })
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%+ -l 1.5"),
  { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%-"),
  { locked = true, repeating = true })

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_SINK@ toggle"), { locked = true })
hl.bind("SUPER+SHIFT + M", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_SINK@ toggle"),
  { locked = true, description = "Toggle mute" })
hl.bind("ALT + XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_SOURCE@ toggle"), { locked = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_SOURCE@ toggle"), { locked = true })
hl.bind("SUPER+ALT + M", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_SOURCE@ toggle"),
  { locked = true, description = "Toggle mic" })
hl.bind("CTRL+SUPER + T", hl.dsp.global("quickshell:wallpaperSelectorToggle"),
  { description = "Toggle wallpaper selector" })
hl.bind("CTRL+SUPER+ALT + T", hl.dsp.global("quickshell:wallpaperSelectorRandom"),
  { description = "Select random wallpaper" })
hl.bind("CTRL+SUPER + T",
  hl.dsp.exec_cmd("qs -c " ..
    QsConfig .. " ipc call TEST_ALIVE || ~/.config/quickshell/" .. QsConfig .. "/scripts/colors/switchwall.sh"),
  { description = "Change wallpaper" })
hl.bind("CTRL+SUPER + R", hl.dsp.exec_cmd("killall ags agsv1 gjs ydotool qs quickshell; qs -c " .. QsConfig .. " &"))
hl.bind("CTRL+SUPER + P", hl.dsp.global("quickshell:panelFamilyCycle"))

--#! Utilities
-- Screenshot, Record, OCR, Color picker, Clipboard history
hl.bind("SUPER + V",
  hl.dsp.exec_cmd("qs -c " ..
    QsConfig ..
    " ipc call TEST_ALIVE || pkill fuzzel || cliphist list | fuzzel --match-mode fzf --dmenu | cliphist decode | wl-copy"),
  { description = "Copy clipboard history entry" })
hl.bind("SUPER + Period",
  hl.dsp.exec_cmd("qs -c " ..
    QsConfig .. " ipc call TEST_ALIVE || pkill fuzzel || ~/.config/hypr/hyprland/scripts/fuzzel-emoji.sh copy"),
  { description = "Copy an emoji" })
hl.bind("SUPER+SHIFT + S", hl.dsp.global("quickshell:regionScreenshot"))
hl.bind("SUPER+SHIFT + S",
  hl.dsp.exec_cmd("qs -c " ..
    QsConfig .. " ipc call TEST_ALIVE || pidof slurp || hyprshot --freeze --clipboard-only --mode region --silent"))
hl.bind("SUPER+SHIFT + A", hl.dsp.global("quickshell:regionSearch"))
hl.bind("SUPER+SHIFT + A",
  hl.dsp.exec_cmd("qs -c " ..
    QsConfig .. " ipc call TEST_ALIVE || pidof slurp || ~/.config/hypr/hyprland/scripts/snip_to_search.sh"))
-- OCR
hl.bind("SUPER+SHIFT + X", hl.dsp.global("quickshell:regionOcr"))
hl.bind("SUPER+SHIFT + T", hl.dsp.global("quickshell:regionOcr"))
hl.bind("SUPER+SHIFT + X",
  hl.dsp.exec_cmd(
    "qs -c " ..
    QsConfig ..
    " ipc call TEST_ALIVE || pidof slurp || grim -g \"$(slurp $SLURP_ARGS)\" \"/tmp/ocr_image.png\" && tesseract \"/tmp/ocr_image.png\" stdout -l $(tesseract --list-langs | awk 'NR>1{print $1}' | tr '\\\\n' '+' | sed 's/\\\\+$/\\\\n/') | wl-copy && rm \"/tmp/ocr_image.png\""))
hl.bind("SUPER+SHIFT + T",
  hl.dsp.exec_cmd(
    "qs -c " ..
    QsConfig ..
    " ipc call TEST_ALIVE || pidof slurp || grim -g \"$(slurp $SLURP_ARGS)\" \"/tmp/ocr_image.png\" && tesseract \"/tmp/ocr_image.png\" stdout -l $(tesseract --list-langs | awk 'NR>1{print $1}' | tr '\\\\n' '+' | sed 's/\\\\+$/\\\\n/') | wl-copy && rm \"/tmp/ocr_image.png\""))
-- Color picker
hl.bind("SUPER+SHIFT + C", hl.dsp.exec_cmd("hyprpicker -a"), { description = "Color picker" })
-- Fullscreen screenshot
hl.bind("Print", hl.dsp.exec_cmd("grim - | wl-copy"), { locked = true })
hl.bind("CTRL + Print",
  hl.dsp.exec_cmd(
    "mkdir -p $(xdg-user-dir PICTURES)/Screenshots && grim $(xdg-user-dir PICTURES)/Screenshots/Screenshot_\"$(date '+%Y-%m-%d_%H.%M.%S')\".png"),
  { locked = true, non_consuming = true })
hl.bind("CTRL + Print", hl.dsp.exec_cmd("grim - | wl-copy"), { locked = true, non_consuming = true })
-- Recording stuff
hl.bind("SUPER+SHIFT + R", hl.dsp.global("quickshell:regionRecord"), { locked = true })
hl.bind("SUPER+SHIFT + R",
  hl.dsp.exec_cmd("qs -c " ..
    QsConfig .. " ipc call TEST_ALIVE || ~/.config/quickshell/" .. QsConfig .. "/scripts/videos/record.sh"),
  { locked = true })
hl.bind("SUPER+ALT + R", hl.dsp.global("quickshell:regionRecord"), { locked = true })
hl.bind("SUPER+ALT + R",
  hl.dsp.exec_cmd("qs -c " .. QsConfig ..
    " ipc call TEST_ALIVE || ~/.config/quickshell/" .. QsConfig .. "/scripts/videos/record.sh"),
  { locked = true })
hl.bind("CTRL+ALT + R", hl.dsp.exec_cmd("~/.config/quickshell/" .. QsConfig .. "/scripts/videos/record.sh --fullscreen"),
  { locked = true })
hl.bind("SUPER+SHIFT+ALT + R",
  hl.dsp.exec_cmd("~/.config/quickshell/" .. QsConfig .. "/scripts/videos/record.sh --fullscreen --sound"),
  { locked = true })
-- AI
hl.bind("SUPER+SHIFT+ALT + mouse:273", hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/ai/primary-buffer-query.sh"),
  { description = "Generate AI summary for selected text" })

--!
--#! Window
-- Focusing
hl.bind("SUPER + mouse:272", hl.dsp.window.drag())
hl.bind("SUPER + mouse:274", hl.dsp.window.drag())
hl.bind("SUPER + mouse:273", hl.dsp.window.resize())
--/# bind = SUPER, ←/↑/→/↓,, # Focus in direction

hl.bind("SUPER + J", hl.dsp.layout("cyclenext"))
hl.bind("SUPER + K", hl.dsp.layout("cycleprev"))
hl.bind("SUPER + Return", hl.dsp.layout("swapwithmaster master"))

-- bind = SUPER, H, movefocus, l # [hidden]
-- bind = SUPER, L, movefocus, r # [hidden]
-- bind = SUPER, K, movefocus, u # [hidden]
-- bind = SUPER, J, movefocus, d # [hidden]
-- bind = SUPER, BracketLeft, movefocus, l # [hidden]
-- bind = SUPER, BracketRight, movefocus, r # [hidden]

--/# bind = SUPER+SHIFT, ←/↑/→/↓,, # Move in direction

-- bind = SUPER+SHIFT, Left, movewindow, l # [hidden]
-- bind = SUPER+SHIFT, Right, movewindow, r # [hidden]
-- bind = SUPER+SHIFT, Up, movewindow, u # [hidden]
-- bind = SUPER+SHIFT, Down, movewindow, d # [hidden]
hl.bind("ALT + F4", hl.dsp.window.close())
hl.bind("SUPER + Q", hl.dsp.window.close())
hl.bind("SUPER+SHIFT+ALT + Q", hl.dsp.exec_cmd("hyprctl kill"))

-- Window split ratio
--/# binde = SUPER, ;/',, # Adjust split ratio
-- Positioning mode
hl.bind("SUPER+SHIFT + Space", hl.dsp.window.float({ action = "toggle" }))
hl.bind("SUPER + M", hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }))
hl.bind("SUPER + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind("SUPER+ALT + F", hl.dsp.window.fullscreen_state({ internal = 0, client = 3, action = "toggle" }))
hl.bind("SUPER + P", hl.dsp.window.pin())

--/# bind = SUPER+SHIFT, Hash,, # Send to workspace # (1, 2, 3,...)
-- We use raw keycodes because some keyboard layouts register number keys as different chars. The codes can be verified with `wev`
hl.bind("SUPER+SHIFT + code:10",
  hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspacesilent 1"))
hl.bind("SUPER+SHIFT + code:11",
  hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspacesilent 2"))
hl.bind("SUPER+SHIFT + code:12",
  hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspacesilent 3"))
hl.bind("SUPER+SHIFT + code:13",
  hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspacesilent 4"))
hl.bind("SUPER+SHIFT + code:14",
  hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspacesilent 5"))
hl.bind("SUPER+SHIFT + code:15",
  hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspacesilent 6"))
hl.bind("SUPER+SHIFT + code:16",
  hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspacesilent 7"))
hl.bind("SUPER+SHIFT + code:17",
  hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspacesilent 8"))
hl.bind("SUPER+SHIFT + code:18",
  hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspacesilent 9"))
hl.bind("SUPER+SHIFT + code:19",
  hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspacesilent 10"))
-- keypad numbers
hl.bind("SUPER+SHIFT + code:87",
  hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspacesilent 1"))
hl.bind("SUPER+SHIFT + code:88",
  hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspacesilent 2"))
hl.bind("SUPER+SHIFT + code:89",
  hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspacesilent 3"))
hl.bind("SUPER+SHIFT + code:83",
  hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspacesilent 4"))
hl.bind("SUPER+SHIFT + code:84",
  hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspacesilent 5"))
hl.bind("SUPER+SHIFT + code:85",
  hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspacesilent 6"))
hl.bind("SUPER+SHIFT + code:79",
  hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspacesilent 7"))
hl.bind("SUPER+SHIFT + code:80",
  hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspacesilent 8"))
hl.bind("SUPER+SHIFT + code:81",
  hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspacesilent 9"))
hl.bind("SUPER+SHIFT + code:90",
  hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspacesilent 10"))

-- #/# bind = SUPER+SHIFT, Scroll ↑/↓,, # Send to workspace left/right
hl.bind("SUPER+SHIFT + mouse_down", hl.dsp.window.move({ workspace = "r-1" }))
hl.bind("SUPER+SHIFT + mouse_up", hl.dsp.window.move({ workspace = "r+1" }))
hl.bind("SUPER+ALT + mouse_down", hl.dsp.window.move({ workspace = -1 }))
hl.bind("SUPER+ALT + mouse_up", hl.dsp.window.move({ workspace = "+1" }))

--/# bind = SUPER+SHIFT, Page_↑/↓,, # Send to workspace left/right
hl.bind("SUPER+ALT + Page_Down", hl.dsp.window.move({ workspace = "+1" }))
hl.bind("SUPER+ALT + Page_Up", hl.dsp.window.move({ workspace = -1 }))
hl.bind("SUPER+SHIFT + Page_Down", hl.dsp.window.move({ workspace = "r+1" }))
hl.bind("SUPER+SHIFT + Page_Up", hl.dsp.window.move({ workspace = "r-1" }))
hl.bind("CTRL+SUPER+SHIFT + Right", hl.dsp.window.move({ workspace = "r+1" }))
hl.bind("CTRL+SUPER+SHIFT + Left", hl.dsp.window.move({ workspace = "r-1" }))

hl.bind("SUPER+ALT + S", hl.dsp.window.move({ workspace = "special", follow = false }))

hl.bind("CTRL+SUPER + S", hl.dsp.workspace.toggle_special(""))

--#! Workspace
-- Switching
--/# bind = SUPER, Hash,, # Focus workspace # (1, 2, 3,...)
-- We use raw keycodes because some keyboard layouts register number keys as different chars. The codes can be verified with `wev`
hl.bind("SUPER + code:10", hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh workspace 1"))
hl.bind("SUPER + code:11", hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh workspace 2"))
hl.bind("SUPER + code:12", hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh workspace 3"))
hl.bind("SUPER + code:13", hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh workspace 4"))
hl.bind("SUPER + code:14", hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh workspace 5"))
hl.bind("SUPER + code:15", hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh workspace 6"))
hl.bind("SUPER + code:16", hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh workspace 7"))
hl.bind("SUPER + code:17", hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh workspace 8"))
hl.bind("SUPER + code:18", hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh workspace 9"))
hl.bind("SUPER + code:19", hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh workspace 10"))
-- keypad numbers
hl.bind("SUPER + code:87", hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh workspace 1"),
  { dont_inhibit = true })
hl.bind("SUPER + code:88", hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh workspace 2"),
  { dont_inhibit = true })
hl.bind("SUPER + code:89", hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh workspace 3"),
  { dont_inhibit = true })
hl.bind("SUPER + code:83", hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh workspace 4"),
  { dont_inhibit = true })
hl.bind("SUPER + code:84", hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh workspace 5"),
  { dont_inhibit = true })
hl.bind("SUPER + code:85", hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh workspace 6"),
  { dont_inhibit = true })
hl.bind("SUPER + code:79", hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh workspace 7"),
  { dont_inhibit = true })
hl.bind("SUPER + code:80", hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh workspace 8"),
  { dont_inhibit = true })
hl.bind("SUPER + code:81", hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh workspace 9"),
  { dont_inhibit = true })
hl.bind("SUPER + code:90", hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh workspace 10"),
  { dont_inhibit = true })

--/# bind = SUPER+Tab # Switch to previous workspace
hl.bind("SUPER + Tab", hl.dsp.focus({ workspace = "previous" }))

--/# bind = CTRL+SUPER, ←/→,, # Focus left/right
hl.bind("CTRL+SUPER + Right", hl.dsp.focus({ workspace = "r+1" }))
hl.bind("CTRL+SUPER + Left", hl.dsp.focus({ workspace = "r-1" }))
--/# bind = CTRL+SUPER+ALT, ←/→,, # [hidden] Focus busy left/right
hl.bind("CTRL+SUPER+ALT + Right", hl.dsp.focus({ workspace = "m+1" }))
hl.bind("CTRL+SUPER+ALT + Left", hl.dsp.focus({ workspace = "m-1" }))
--/# bind = SUPER, Page_↑/↓,, # Focus left/right
hl.bind("SUPER + Page_Down", hl.dsp.focus({ workspace = "+1" }))
hl.bind("SUPER + Page_Up", hl.dsp.focus({ workspace = -1 }))
hl.bind("CTRL+SUPER + Page_Down", hl.dsp.focus({ workspace = "r+1" }))
hl.bind("CTRL+SUPER + Page_Up", hl.dsp.focus({ workspace = "r-1" }))
--/# bind = SUPER, Scroll ↑/↓,, # Focus left/right
hl.bind("SUPER + mouse_up", hl.dsp.focus({ workspace = "+1" }))
hl.bind("SUPER + mouse_down", hl.dsp.focus({ workspace = -1 }))
hl.bind("CTRL+SUPER + mouse_up", hl.dsp.focus({ workspace = "r+1" }))
hl.bind("CTRL+SUPER + mouse_down", hl.dsp.focus({ workspace = "r-1" }))
--# Special
hl.bind("SUPER + S", hl.dsp.workspace.toggle_special(""))
hl.bind("SUPER + mouse:275", hl.dsp.workspace.toggle_special(""))
hl.bind("CTRL+SUPER + BracketLeft", hl.dsp.focus({ workspace = -1 }))
hl.bind("CTRL+SUPER + BracketRight", hl.dsp.focus({ workspace = "+1" }))
hl.bind("CTRL+SUPER + Up", hl.dsp.focus({ workspace = "r-5" }))
hl.bind("CTRL+SUPER + Down", hl.dsp.focus({ workspace = "r+5" }))

--#! Virtual machines
hl.bind("SUPER+ALT + F1",
  hl.dsp.exec_cmd(
    "notify-send 'Entered Virtual Machine submap' 'Keybinds disabled. Hit SUPER+ALT+F1 to escape' -a 'Hyprland' && hyprctl dispatch submap virtual-machine"))
hl.define_submap("virtual-machine", function()
  hl.bind("SUPER+ALT + F1",
    hl.dsp.exec_cmd(
      "notify-send 'Exited Virtual Machine submap' 'Keybinds re-enabled' -a 'Hyprland' && hyprctl dispatch submap global"))
end)

hl.define_submap("global", function()
  --!
  -- Testing
  hl.bind("SUPER+ALT + f11",
    hl.dsp.exec_cmd(
      "bash -c 'RANDOM_IMAGE=$(find ~/Pictures -type f | grep -v -i \"nipple\" | grep -v -i \"pussy\" | shuf -n 1); ACTION=$(notify-send \"Test notification with body image\" \"This notification should contain your user account <b>image</b> and <a href=\\\"https://discord.com/app\\\">Discord</a> <b>icon</b>. Oh and here is a random image in your Pictures folder: <img src=\\\"$RANDOM_IMAGE\\\" ALT=\\\"Testing image\\\"/>\" -a \"Hyprland keybind\" -p -h \"string:image-path:/var/lib/AccountsService/icons/$USER\" -t 6000 -i \"discord\" -A \"openImage=Profile image\" -A \"action2=Open the random image\" -A \"action3=Useless button\"); [[ $ACTION == *openImage ]] && xdg-open \"/var/lib/AccountsService/icons/$USER\"; [[ $ACTION == *action2 ]] && xdg-open \\\"$RANDOM_IMAGE\\\"'"))
  hl.bind("SUPER+ALT + f12",
    hl.dsp.exec_cmd(
      "bash -c 'RANDOM_IMAGE=$(find ~/Pictures -type f | grep -v -i \"nipple\" | grep -v -i \"pussy\" | shuf -n 1); ACTION=$(notify-send \"Test notification\" \"This notification should contain a random image in your <b>Pictures</b> folder and <a href=\\\"https://discord.com/app\\\">Discord</a> <b>icon</b>.\\n<i>Flick right to dismiss!</i>\" -a \"Discord (fake)\" -p -h \"string:image-path:$RANDOM_IMAGE\" -t 6000 -i \"discord\" -A \"openImage=Profile image\" -A \"action2=Useless button\"); [[ $ACTION == *openImage ]] && xdg-open \"/var/lib/AccountsService/icons/$USER\"'"))
  hl.bind("SUPER+ALT + Equal",
    hl.dsp.exec_cmd("notify-send \"Urgent notification\" \"Ah hell no\" -u critical -a 'Hyprland keybind'"))

  --#! Session
  hl.bind("SUPER+SHIFT + L", hl.dsp.exec_cmd("loginctl lock-session"), { description = "Lock" })
  -- bindld = SUPER+SHIFT, L, Suspend system, exec, systemctl suspend || loginctl suspend # Sleep
  -- bindl=,switch:on:Lid Switch, exec, systemctl suspend || loginctl suspend # [hidden] Suspend when laptop lid is closed, uncomment if for whatever reason it's not the default behavior
  hl.bind("CTRL+SHIFT+ALT+SUPER + Delete", hl.dsp.exec_cmd("systemctl poweroff || loginctl poweroff"),
    { description = "Shutdown" })

  --#! Screen
  -- Zoom
  hl.bind("SUPER + Minus", hl.dsp.exec_cmd("qs -c " .. QsConfig .. " ipc call zoom zoomOut"), { repeating = true })
  hl.bind("SUPER + Equal", hl.dsp.exec_cmd("qs -c " .. QsConfig .. " ipc call zoom zoomIn"), { repeating = true })
  hl.bind("SUPER + Minus",
    hl.dsp.exec_cmd("qs -c " .. QsConfig ..
      " ipc call TEST_ALIVE || ~/.config/hypr/hyprland/scripts/zoom.sh decrease 0.1"),
    { repeating = true })
  hl.bind("SUPER + Equal",
    hl.dsp.exec_cmd("qs -c " .. QsConfig ..
      " ipc call TEST_ALIVE || ~/.config/hypr/hyprland/scripts/zoom.sh increase 0.1"),
    { repeating = true })
  -- Zoom with keypad
  hl.bind("SUPER + code:82", hl.dsp.exec_cmd("qs -c " .. QsConfig .. " ipc call zoom zoomOut"), { repeating = true })
  hl.bind("SUPER + code:86", hl.dsp.exec_cmd("qs -c " .. QsConfig .. " ipc call zoom zoomIn"), { repeating = true })
  hl.bind("SUPER + code:82",
    hl.dsp.exec_cmd("qs -c " .. QsConfig ..
      " ipc call TEST_ALIVE || ~/.config/hypr/hyprland/scripts/zoom.sh decrease 0.1"),
    { repeating = true })
  hl.bind("SUPER + code:86",
    hl.dsp.exec_cmd("qs -c " .. QsConfig ..
      " ipc call TEST_ALIVE || ~/.config/hypr/hyprland/scripts/zoom.sh increase 0.1"),
    { repeating = true })

  --#! Media
  hl.bind("SUPER+SHIFT + N",
    hl.dsp.exec_cmd(
      "playerctl next || playerctl position `bc <<< \"100 * $(playerctl metadata mpris:length) / 1000000 / 100\"`"),
    { locked = true })
  hl.bind("XF86AudioNext",
    hl.dsp.exec_cmd(
      "playerctl next || playerctl position `bc <<< \"100 * $(playerctl metadata mpris:length) / 1000000 / 100\"`"),
    { locked = true })
  hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })
  hl.bind("SUPER+SHIFT+ALT + mouse:275", hl.dsp.exec_cmd("playerctl previous"))
  hl.bind("SUPER+SHIFT+ALT + mouse:276",
    hl.dsp.exec_cmd(
      "playerctl next || playerctl position `bc <<< \"100 * $(playerctl metadata mpris:length) / 1000000 / 100\"`"))
  hl.bind("SUPER+SHIFT + B", hl.dsp.exec_cmd("playerctl previous"), { locked = true })
  hl.bind("SUPER+SHIFT + P", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
  hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
  hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

  --#! Apps
  -- bind = SUPER, Return, exec, ~/.config/hypr/hyprland/scripts/launch_first_available.sh "${TERMINAL}" "kitty -1" "foot" "alacritty" "wezterm" "konsole" "kgx" "uxterm" "xterm" # Terminal
  -- bind = SUPER, T, exec, ~/.config/hypr/hyprland/scripts/launch_first_available.sh  "${TERMINAL}" "kitty -1" "foot" "alacritty" "wezterm" "konsole" "kgx" "uxterm" "xterm" # [hidden] (terminal) (ALT)
  -- bind = CTRL+ALT, T, exec, ~/.config/hypr/hyprland/scripts/launch_first_available.sh "${TERMINAL}" "kitty -1" "foot" "alacritty" "wezterm" "konsole" "kgx" "uxterm" "xterm" # [hidden] (terminal) (for Ubuntu people)
  -- bind = SUPER, E, exec, ~/.config/hypr/hyprland/scripts/launch_first_available.sh "dolphin" "nautilus" "nemo" "thunar" "${TERMINAL}" "kitty -1 fish -c yazi" # File manager
  -- bind = SUPER+SHIFT, B, exec, ~/.config/hypr/hyprland/scripts/launch_first_available.sh "google-chrome-stable" "zen-browser" "firefox" "brave" "chromium" "microsoft-edge-stable" "opera" "librewolf" # Browser
  -- bind = SUPER, C, exec, ~/.config/hypr/hyprland/scripts/launch_first_available.sh "code" "codium" "cursor" "zed" "zedit" "zeditor" "kate" "gnome-text-editor" "emacs" "command -v nvim && kitty -1 nvim" "command -v micro && kitty -1 micro" # Code editor
  -- bind = CTRL+SUPER+SHIFT+ALT, W, exec, ~/.config/hypr/hyprland/scripts/launch_first_available.sh "wps" "onlyoffice-desktopeditors" "libreoffice" # Office software
  -- bind = SUPER, X, exec, ~/.config/hypr/hyprland/scripts/launch_first_available.sh "kate" "gnome-text-editor" "emacs" # Text editor
  -- bind = SHIFT+SUPER, V, exec, ~/.config/hypr/hyprland/scripts/launch_first_available.sh "pavucontrol-qt" "pavucontrol" # Volume mixer
  -- bind = SUPER, I, exec, XDG_CURRENT_DESKTOP=gnome ~/.config/hypr/hyprland/scripts/launch_first_available.sh "qs -p ~/.config/quickshell/".. QsConfig .."/settings.qml" "systemsettings" "gnome-control-center" "better-control" # Settings app
  -- bind = CTRL+SHIFT, Escape, exec, ~/.config/hypr/hyprland/scripts/launch_first_available.sh "gnome-system-monitor" "plasma-systemmonitor --page-name Processes" "command -v btop && kitty -1 fish -c btop" # Task manager

  -- Cursed stuff
  --# Make window not amogus large
  hl.bind("CTRL+SUPER + Backslash", hl.dsp.window.resize({ x = 640, y = 480 }))
end)
