#!/usr/bin/env bash

tmux-sessionizer ()
{
    if [[ $# -eq 1 ]]; then
        selected="$1"
    else
        selected=$(find ~/personal/ ~/nsbm/ ~/Documents/NSBM/ -type d -not -path '*/node_modules*' -not -path '*/.vscode*' -not -path '*/lib/python*' -not -path '*/.git*' | fzf)
    fi

    if [[ -z $selected ]]; then
        return
    fi

    selected_name=$(basename "$selected" | tr . _)
    tmux_running=$(pgrep tmux)

    if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
        tmux new-session -s "$selected_name" -c "$selected"
        return
    fi

    if ! tmux has-session -t="$selected_name" 2> /dev/null; then
        tmux new-session -ds "$selected_name" -c "$selected"
    fi

    if [[ -z $TMUX ]]; then
        tmux attach -t "$selected_name"
    else
        tmux switch-client -t "$selected_name"
    fi

}
